### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by xryst** [RasimAghayev/bond-algoritma#5]
Hi, @RasimAghayev !

For correct your work testing we need issue for each API.

We are interested not only in the result of your work. We need to see how your work is going.

I ask you to create a new **branch**, where for each **issue**, there will be a **commit**

**Comment by RasimAghayev** [comment]
Hi Rustam,
Since the task is in Azerbaijani by your company, you would open the next Issue and write your thoughts in Azerbaijani there.
Respect for our language is a price for our homeland.
